// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_green_biscuit = "CgkI1sSJ7s8GEAIQBA"; // <GPGSID>
        public const string achievement_sweet_cactus = "CgkI1sSJ7s8GEAIQBg"; // <GPGSID>
        public const string achievement_party_cake = "CgkI1sSJ7s8GEAIQAA"; // <GPGSID>
        public const string achievement_chocolate_slice = "CgkI1sSJ7s8GEAIQCA"; // <GPGSID>
        public const string achievement_round_candy = "CgkI1sSJ7s8GEAIQAw"; // <GPGSID>
        public const string achievement_tasty_bun = "CgkI1sSJ7s8GEAIQBQ"; // <GPGSID>
        public const string achievement_fragrant_cake = "CgkI1sSJ7s8GEAIQAg"; // <GPGSID>
        public const string achievement_delicious_lollipop = "CgkI1sSJ7s8GEAIQAQ"; // <GPGSID>
        public const string achievement_double_candy = "CgkI1sSJ7s8GEAIQBw"; // <GPGSID>

}

