#############################################################################
# Makefile for building: GPLauncher.app/Contents/MacOS/GPLauncher
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  GPLauncher.pro
# Template: app
# Command: /Users/it_ra/Qt/5.15.2/clang_static_64/bin/qmake -o GPLauncher.xcodeproj/project.pbxproj GPLauncher.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/it_ra/Qt/5.15.2/clang_static_64/bin/qmake
GPLauncher.xcodeproj/project.pbxproj: GPLauncher.pro /Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-clang/qmake.conf /Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/spec_pre.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/qdevice.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/device_config.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/unix.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/mac.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/macx.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/sanitize.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/gcc-base.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/gcc-base-mac.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/clang.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/clang-mac.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/qconfig.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_core.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_help.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_location.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_network.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_script.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_assimp.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_openglrenderer.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qcocoa.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qgif.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qico.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacstyle.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtexttospeech_speechosx.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwebgl.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_scene2d.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_uip.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt_functions.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt_config.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-clang/qmake.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-xcode/qmake.conf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/spec_post.prf \
		/Users/it_ra/.qmake.stash \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/exclusive_builds.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/sdk.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/toolchain.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/toolchain.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/default_pre.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/default_pre.prf \
		ui/ui.pri \
		localization/localization.pri \
		version.pri \
		core/core.pri \
		config/config.pri \
		helpers/helpers.pri \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resolve_config.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/default_post.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/default_post.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/objective_c.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/mac.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/warn_on.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/gc_binaries.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resources_functions.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resources.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/moc.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/unix/opengl.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/unix/thread.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qmake_use.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/file_copies.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/rez.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/testcase_targets.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/exceptions.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/yacc.prf \
		/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/lex.prf \
		GPLauncher.pro \
		ui/qml.qrc \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/platforms/libqcocoa_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqgif_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqicns_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqico_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqjpeg_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqmacheif_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqmacjp2_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqtga_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqtiff_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqwbmp_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqwebp_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_debugger_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_inspector_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_local_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_messages_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_native_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_nativedebugger_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_preview_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_profiler_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_server_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_tcp_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/bearer/libqgenericbearer_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/printsupport/libcocoaprintersupport_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/styles/libqmacstyle_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Quick_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Gui_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5QmlModels_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Qml_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Network_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Core_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick.2/libqtquick2plugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/libqmlplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/Models.2/libmodelsplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/WorkerScript.2/libworkerscriptplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Window.2/libwindowplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin_debug.prl \
		/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin_debug.prl
	$(QMAKE) -o GPLauncher.xcodeproj/project.pbxproj GPLauncher.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/spec_pre.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/qdevice.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/device_config.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/unix.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/mac.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/macx.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/sanitize.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/gcc-base.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/gcc-base-mac.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/clang.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/common/clang-mac.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/qconfig.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_charts.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_core.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designer.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gui.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_help.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_location.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_network.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qml.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3d.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3drender.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_script.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sql.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_svg.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webview.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xml.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_assimp.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_darwingamepad.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_openglrenderer.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qcocoa.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qgif.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qicns.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qico.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qjpeg.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacheif.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmacstyle.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtexttospeech_speechosx.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtga.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qttinycanbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwebgl.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_scene2d.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/modules/qt_plugin_uip.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt_functions.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt_config.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-clang/qmake.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-xcode/qmake.conf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/spec_post.prf:
/Users/it_ra/.qmake.stash:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/exclusive_builds.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/sdk.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/toolchain.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/toolchain.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/default_pre.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/default_pre.prf:
ui/ui.pri:
localization/localization.pri:
version.pri:
core/core.pri:
config/config.pri:
helpers/helpers.pri:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resolve_config.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/default_post.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/default_post.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/objective_c.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/mac.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/warn_on.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qt.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/gc_binaries.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resources_functions.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/resources.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/moc.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/unix/opengl.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/unix/thread.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/qmake_use.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/file_copies.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/rez.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/testcase_targets.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/exceptions.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/yacc.prf:
/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/features/lex.prf:
GPLauncher.pro:
ui/qml.qrc:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/platforms/libqcocoa_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqgif_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqicns_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqico_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqjpeg_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqmacheif_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqmacjp2_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqtga_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqtiff_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqwbmp_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/imageformats/libqwebp_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_debugger_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_inspector_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_local_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_messages_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_native_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_nativedebugger_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_preview_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_profiler_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_server_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/qmltooling/libqmldbg_tcp_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/bearer/libqgenericbearer_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/printsupport/libcocoaprintersupport_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/plugins/styles/libqmacstyle_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Quick_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Gui_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5QmlModels_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Qml_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Network_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/lib/libQt5Core_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick.2/libqtquick2plugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/libqmlplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/Models.2/libmodelsplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQml/WorkerScript.2/libworkerscriptplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Window.2/libwindowplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin_debug.prl:
/Users/it_ra/Qt/5.15.2/clang_static_64/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin_debug.prl:
qmake: FORCE
	@$(QMAKE) -o GPLauncher.xcodeproj/project.pbxproj GPLauncher.pro -spec macx-xcode

qmake_all: FORCE

