#############################################################################
# Makefile for building: GPLauncher.app/Contents/MacOS/GPLauncher
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  GPLauncher.pro
# Template: app
# Command: /Users/it_ra/Qt/5.15.2/clang_static_64/bin/qmake -o GPLauncher.xcodeproj/project.pbxproj GPLauncher.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DAPP_VERSION=\"1.4.3.1\" -DAPP_VERSION_ALT=\"1,4,3,1\" -DAPP_VERSION=\"1.4.3.1\" -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DAPI_V1 -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH       = -I. -Iinclude -Iinclude/zlib -Iinclude/quazip -Iinclude/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/it_ra/Qt/5.15.2/clang_static_64/mkspecs/macx-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_qml.cpp moc_form.cpp moc_appPhase.cpp moc_application.cpp\
	 moc_network.cpp moc_servers.cpp moc_storage.cpp\
	 moc_updatePhase.cpp
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: ui/qml.qrc \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/rcc \
		ui/qml/Download.qml \
		ui/qml/Main.qml \
		ui/qml/ConnectionLost.qml \
		ui/qml/Connect.qml \
		ui/qml/ErrorConnect.qml \
		ui/image/CloseButton.png \
		ui/image/BackAnim.gif \
		ui/image/ProgressBarBack.png \
		ui/image/GoldButton.png \
		ui/image/TryAgaineButton.png \
		ui/image/GoldGrad.png \
		ui/fonts/Montserrat-SemiBold.otf
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/rcc -name qml ui/qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_form.cpp moc_appPhase.cpp moc_application.cpp moc_network.cpp moc_servers.cpp moc_storage.cpp moc_updatePhase.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_form.cpp moc_appPhase.cpp moc_application.cpp moc_network.cpp moc_servers.cpp moc_storage.cpp moc_updatePhase.cpp
moc_form.cpp: ui/form.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml/QQmlApplicationEngine \
		core/appPhase.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include ui/form.h -o moc_form.cpp

moc_appPhase.cpp: core/appPhase.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/appPhase.h -o moc_appPhase.cpp

moc_application.cpp: core/application.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml/QQmlApplicationEngine \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork/QNetworkReply \
		core/record.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QString \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QJsonObject \
		core/appPhase.h \
		core/updatePhase.h \
		include/quazip/quazip.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/application.h -o moc_application.cpp

moc_network.cpp: core/network.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork/QtNetwork \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork/QNetworkAccessManager \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork/QNetworkReply \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/network.h -o moc_network.cpp

moc_servers.cpp: core/servers.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QJsonObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QJsonArray \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QByteArray \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/servers.h -o moc_servers.cpp

moc_storage.cpp: core/storage.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QSettings \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QDebug \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/storage.h -o moc_storage.cpp

moc_updatePhase.cpp: core/updatePhase.h \
		/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore/QObject \
		/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc
	/Users/it_ra/Qt/5.15.2/clang_static_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -Imacx-xcode -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/zlib -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/quazip -I/Users/it_ra/Documents/work/GarillaPoker/Launcher/GPLauncher/include/rsa -I/Users/it_ra/Qt/5.15.2/clang_static_64/include -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQuick -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtGui -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQmlModels -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtQml -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtNetwork -I/Users/it_ra/Qt/5.15.2/clang_static_64/include/QtCore -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include core/updatePhase.h -o moc_updatePhase.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

